name: Daily sync from the upstream

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00 on every day

jobs:
  bash-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.0.0.b
        with:
          upstream_repo: "https://github.com/FiloSottile/mkcert.git"
          upstream_branch: master
          downstream_branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
